export const adminIds = ["110848584724724596345"];
export const initialTags= [
    "Software Engineer",
    "Full Stack Developer",
    "Front End Developer",
    "Back End Developer",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "Data Analyst",
    "Data Science",
    "Data Analytics",
    "DevOps Engineer",
    "Cloud Engineer",
    "Cybersecurity Engineer",
    "AI Engineer",
    "Systems Architect",
    "Network Engineer",
    "Java Developer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "C++ Developer",
    "Software Tester",
    "UI/UX Designer",
    "Web Developer",
];